In [5]:
import pandas as pd
import numpy as np

In [13]:
ar1 = np.array([0, 1, 2, 3]) # 1D dimensional array
ar2 = np.array([[0, 1], [2, 3]]) # 2D dimensional array

In [15]:
ar2

array([[0, 1],
       [2, 3]])

In [18]:
ar1.shape

(4,)

In [20]:
ar3 = np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
ar4 = np.arange(3, 10, 3)
ar4

array([3, 6, 9])

In [28]:
ar5 = np.linspace(2, 3/4, 9)
ar5

array([2.     , 1.84375, 1.6875 , 1.53125, 1.375  , 1.21875, 1.0625 ,
       0.90625, 0.75   ])

In [33]:
ar7 = np.ones((2, 3, 2))
ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [37]:
ar8 = np.zeros((3, 2, 4))
ar8

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
f_ar = np.array([1, 4, 6])
f_ar

array([1, 4, 6])

In [45]:
ar10 = np.diag((1, 3, 4, 7))
ar10

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 7]])

In [49]:
np.random.seed(100)
ar11 = np.random.rand(3)
ar11

array([0.54340494, 0.27836939, 0.42451759])